# GitHub Actions workflow to cross-compile tinyalsa-ndk with Android NDK
# - Targets Android 15 (API level 35) by default (APP_PLATFORM=android-35)
# - Builds using ndk-build and the repository's jni/Android.mk
# - Produces libs/<ABI> artifacts (arm64-v8a and armeabi-v7a by default)
name: CI / Android NDK Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-android:
    name: Build (Android NDK)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        abi: [arm64-v8a, armeabi-v7a]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install utilities
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip curl

      - name: Download Android NDK r25c
        # r25c is chosen as a reasonably recent, stable NDK that supports modern Android API levels.
        run: |
          set -eux
          NDK_VERSION="r25c"
          NDK_ZIP="android-ndk-${NDK_VERSION}-linux.zip"
          NDK_URL="https://dl.google.com/android/repository/${NDK_ZIP}"
          curl -fsSL "$NDK_URL" -o "$NDK_ZIP"
          unzip -q "$NDK_ZIP" -d $HOME
          echo "ANDROID_NDK_HOME=$HOME/android-ndk-${NDK_VERSION}" >> $GITHUB_ENV
          echo "$HOME/android-ndk-${NDK_VERSION}" > ndk-path.txt

      - name: Show ndk-build path
        run: |
          echo "NDK path: $ANDROID_NDK_HOME"
          ls -la "$ANDROID_NDK_HOME"

      - name: Run ndk-build for ABI
        env:
          ANDROID_NDK_HOME: ${{ env.ANDROID_NDK_HOME }}
        run: |
          set -eux
          # Override Android platform to target Android 15 (API 35). Adjust APP_PLATFORM if you want a different API.
          APP_PLATFORM="android-35"
          ABI="${{ matrix.abi }}"
          export PATH="$ANDROID_NDK_HOME:$PATH"
          # Ensure we run ndk-build in repo root (Android.mk is under jni/)
          if [ -x "$ANDROID_NDK_HOME/ndk-build" ]; then
            echo "Running ndk-build for ABI=${ABI} APP_PLATFORM=${APP_PLATFORM}"
            "$ANDROID_NDK_HOME/ndk-build" -j$(nproc) NDK_PROJECT_PATH=. APP_ABI="${ABI}" APP_PLATFORM="${APP_PLATFORM}" NDK_OUT=out/ndk-out NDK_LIBS_OUT=libs || (echo "ndk-build failed"; exit 1)
          else
            echo "ndk-build not found at $ANDROID_NDK_HOME/ndk-build"
            exit 1
          fi

      - name: List produced libraries
        run: |
          echo "libs directory contents:"
          if [ -d libs ]; then
            find libs -maxdepth 3 -type f -print || true
          else
            echo "No libs/ directory produced."
          fi

      - name: Upload Android artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tinyalsa-android-${{ matrix.abi }}
          path: |
            libs/${{ matrix.abi }}/**
            out/ndk-out/**
