name: Build tinyalsa-ndk Binaries

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build tinyalsa-ndk binaries
        run: |
          docker run --rm -v $PWD:/build ykasidit/android_ndk_c_rust_go_builder:latest \
          bash -c "cd /build && ndk-build clean && ndk-build -j $(nproc)"

      - name: List built binaries
        run: |
          echo "=== ARM64-v8a binaries ==="
          ls -l libs/arm64-v8a/tiny*
          echo "=== armeabi-v7a binaries ==="
          ls -l libs/armeabi-v7a/tiny*

      - name: Upload ARM64 binaries
        uses: actions/upload-artifact@v3
        with:
          name: tinyalsa-arm64-v8a
          path: libs/arm64-v8a/tiny*

      - name: Upload ARMv7 binaries
        uses: actions/upload-artifact@v3
        with:
          name: tinyalsa-armeabi-v7a
          path: libs/armeabi-v7a/tiny*
